# Generated by Django 5.1.2 on 2024-10-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slottimeevening',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slottimemorning',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
