# Generated by Django 5.1.2 on 2024-10-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_alter_slottimeevening_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slottimeevening',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='slottimemorning',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Receptionists',
        ),
        migrations.DeleteModel(
            name='SlotTimeEvening',
        ),
        migrations.DeleteModel(
            name='SlotTimeMorning',
        ),
    ]
